name: Monitor Treni Bassano

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:       

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa librerie
        run: pip install requests beautifulsoup4 python-telegram-bot

      - name: Esegui lo script
        env:
          # QUI C'È IL TRUCCO: 
          # Colleghiamo i Secrets di GitHub alle variabili che Python leggerà
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py  # <-- ATTENZIONE: metti il nome reale del tuo file .py